Sprint#9
AlexanderSharygin/java-filmorate pull request #1
Opened 2022-09-15 17:01 UTC by AlexanderSharygin

2022-09-15 17:19 UTC, AlexanderSharygin commented
Добрый день, к сожалению, тесты упали по причине. Как я понял это случилось по тому что сделал немного по другому свой проект. В моем проекте пользователи обновляются по совпадению email, а фильмы по совпадению названия/даты выпуска. Тогда как в тестах обновление предусматривается по id. Я в проекте написал свои собственные тесты.  Честно говоря, не очень бы хотелось править логику (так как в задании не было сказано как обновлять сущности, и я сделал вариант который, показался мне наиболее правильным)

2022-09-15 19:36 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-09-15 19:36 UTC, FanaticFiz commented on pom.xml
> +		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
В этом файле тоже можно использовать переменные. 
И зачастую делают так: 
```
<java.version>11</java.version>
<maven.compiler.release>${java.version}</maven.compiler.release>
```

2022-09-15 19:36 UTC, FanaticFiz commented on pom.xml
> +			<groupId>com.google.code.gson</groupId>
Эта зависимость лишняя

2022-09-15 19:36 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +import java.time.LocalDate;
Не используемые импорты

2022-09-15 19:36 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ExceptionApiHandler.java
> +                .status(HttpStatus.BAD_REQUEST)
Для `AlreadyExist` есть свой статус HttpStatus код

2022-09-15 19:36 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ExceptionApiHandler.java
> +                .status(HttpStatus.BAD_REQUEST)
Для `NotExistException` тоже есть свой код.

Вообще ты себе усложнил вводную работу. 
Тут не должно было быть еще этого... исключения и их обработка вводится на следующих этапах.
На этом же этапе ты должен был поработать с валидацией, разобраться и подключить библиотеку для этого.
Ну в общем не туда ты подался.

2022-09-15 19:36 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public ResponseEntity<?> create(@RequestBody Film film) {
Надо переделать чтобы проходили тесты...
Это только начало, кода еще не много, впереди два месяца работы по этому проекту. Мы не можем игнорить тесты!

Ну слушай, у меня на работе сегодня же случилась подобная ситуация, да и вообще такое происходит регулярно. 
Я сейчас работаю над фичей подключения DFX файлов к проекту, залетать они должны как слои, и у нас есть несколько типов слоёв.
Ну и вот я подумал что слои должны быть растровыми а менеджер говорит что слои должны быть векторными, а это прям пипец какая разница.
Завтра я еще оспаривать буду, так как пока технически не могу сделать его векторным. Но боюсь придётся еще какой нить модуль перепиливать.

Очень сложно отказаться от написанного кода, очень сложно признать и пойти исправлять ошибки в своём коде...

2022-09-15 19:36 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmAlreadyExistsException.java
> +public class FilmAlreadyExistsException extends RuntimeException {
По исключениям...
Не делаем исключения для каждого класса своё.
Должно быть общее: `AlreadyExistsException`

И так по каждому типу исключения... NotFoundException, BadRequestException

2022-09-15 19:36 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Duration duration;
Длительность можно сделать просто `long`
`private long duration; // minutes`

Да и как то ты загнался конечно с releaseDate с сереализацией/десереализацией
@JsonDeserialize(using = LocalDateDeserializer.class)
@JsonSerialize(using = LocalDateSerializer.class)
private LocalDate releaseDate;
    
Чёт мне кажется она и так должна работать, хотя я давно не собирал вот так с нуля проекты.

2022-09-15 19:36 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Integer id;
Integer мало Long оптимальное для id

2022-09-15 19:36 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +package ru.yandex.practicum.filmorate.model;
Следуй единому принципу именования пакетов. Определись во множественном числе или единственном тебе сейчас кажется более уместным. Но точно не в разнобой: controllers / exceptions / model

2022-09-15 19:36 UTC, FanaticFiz commented on src/main/resources/application.properties
> +server.port=8080
Я буду топить за то чтобы ты сразу привыкал к написанию файла свойств для приложения в формате `yaml -> application.yml`

Соответственно - попрошу тебя этому следовать.
Как мини задание: посмотри как задавать порт для сервиса отличный от дефолтного и случайный.
(Сам порт менять не нужно, сломаются тесты)

2022-09-15 19:36 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +            user.setName(user.getLogin());
Мне нравится что при валидации идёт изменение сущности...
Валидация отдельно, а вот это правило - формирования имени пользователя, это уже похоже на бизнес логику, она должна быть реализована отдельно.

2022-09-16 16:08 UTC, AlexanderSharygin commented on pom.xml
> +		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
Fixed

2022-09-16 16:08 UTC, AlexanderSharygin commented on pom.xml
> +			<groupId>com.google.code.gson</groupId>
Fixed

2022-09-16 16:08 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +import java.time.LocalDate;
fixed

2022-09-16 16:15 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ExceptionApiHandler.java
> +                .status(HttpStatus.BAD_REQUEST)
FIxed

2022-09-16 16:19 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ExceptionApiHandler.java
> +                .status(HttpStatus.BAD_REQUEST)
Fixed. Но, честно говоря в задании как раз и было сказано "Подсказка: как обработать ошибки
Для обработки ошибок валидации напишите новое исключение — например, ValidationException."
Я по этому и добавил эксепшены, предварительно погуглив как это реализуется.
Про библиотеку - было задание под звездчкой*

2022-09-16 16:22 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmAlreadyExistsException.java
> +public class FilmAlreadyExistsException extends RuntimeException {
Fixed

2022-09-16 16:26 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Duration duration;
FIxed. Насчет сериализации - мне же в любом случае надо как то дату к определённому формату приводить - поэтом я так и заморочился (мне показалось это самым простым способом с учетом того то под капотом крутится jackson)

2022-09-16 16:27 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Integer id;
Fixed

2022-09-16 16:40 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +            user.setName(user.getLogin());
Fixed

2022-09-16 17:00 UTC, AlexanderSharygin commented on src/main/resources/application.properties
> +server.port=8080
Fixed

2022-09-16 18:08 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public ResponseEntity<?> create(@RequestBody Film film) {
fixed

2022-09-16 20:30 UTC, AlexanderSharygin commented
Поправил все замечания + поработал с валидацией при помощи библиотеки спринга

2022-09-17 17:34 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ExceptionApiHandler.java
> +                .status(HttpStatus.BAD_REQUEST)
С эксепшенами понятно, я тебя не отговариваю )
А с валидацией советую не затягивать, она сэкономит тебе время, минимальными усилиями.

2022-09-17 17:53 UTC, FanaticFiz approved these changes
Финальный комментарий на Я.Практикуме

2022-09-17 17:53 UTC, FanaticFiz commented on pom.xml
> +		<java.version>11</java.version>
Куда потерялось указание кодировки? UTF-8
Это было правильно сделано!

2022-09-17 17:53 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ExceptionApiHandler.java
> +        String message = e.getBindingResult().getFieldErrors().stream().map(FieldError::getField).findFirst().get() + " - " +
Вот такую "лапшу", которая написана через точку, следует переносить, каждая новая операция с новой строки...
Сама строка сильно перегружена и использует очень длинное `e.getBindingResult().getFieldErrors().stream()` дважды... 
нужен рефакторинг...

2022-09-17 17:53 UTC, FanaticFiz commented on src/main/resources/application.yml
> +server.port: 8080
на yaml это выглядит так:

```
server:
  port: 8080
```

2022-09-18 17:00 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ExceptionApiHandler.java
> +        String message = e.getBindingResult().getFieldErrors().stream().map(FieldError::getField).findFirst().get() + " - " +
Fixed

2022-09-18 17:02 UTC, AlexanderSharygin commented on src/main/resources/application.yml
> +server.port: 8080
fixed

2022-09-18 17:07 UTC, AlexanderSharygin commented on pom.xml
> +		<java.version>11</java.version>
Fixed

2022-09-18 17:11 UTC, merged