Add friends likes
AlexanderSharygin/java-filmorate pull request #2
Opened 2022-09-29 17:18 UTC by AlexanderSharygin

2022-09-29 20:14 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-09-29 20:14 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +
Так так, что за лишняя пустая строка... ))
На ревью это всё видно, обычно я заставляю сдающего самостоятельно всё просмотреть перед сдачей. И обычно такие мелочи отсеиваются...

2022-09-29 20:14 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +import org.springframework.web.bind.annotation.DeleteMapping;
Обычно такое большое кол-во импортов схлопывается в один...

```
import org.springframework.web.bind.annotation.*;
```

Странные у тебя настройки... Сможешь найти где это?

2022-09-29 20:14 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/IncorrectParameterException.java
> +public class IncorrectParameterException extends RuntimeException {
Да эксепшн мы бросаем по причине неверного параметра... 
Но у нас веб сервис, к нам приходят запросы с этими самыми параметрами, поэтому эксепшн в общем называют `BadRequestException` - некорректный запрос... а в теле уже идёт уточнение какой параметр мы посчитали неверным.

2022-09-29 20:14 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +    @Value("${server.minDate}")
Слушай классно что прокинул так параметр!
Но, ты разместил его в секции `server`. Что неверно. 
Лучше расположить его в своей кастомной секции. 
Ну вот можно прям по названию проекта

```
filmorate:
  minDate: 
```

2022-09-29 20:14 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +        var sorted = films.stream().sorted((f1, f2) -> f2.getLikeUsers().size() - f1.getLikeUsers().size()).collect(Collectors.toList());
Ох как тут всё... Ну да я прям узнаю себя когда только начинал с Java 8+ разбираться )))

- У тебя тут длинная лапша: надо делать каждую отдельную операцию на отдельной строке...
- У тебя тут два раза стрим взят, тогда когда можно было бы продолжить первый...

```
        return films.stream()
                    .sorted((f1, f2) -> f2.getLikeUsers().size() - f1.getLikeUsers().size())
                    .limit(count)
                    .collect(Collectors.toList());
```

- У тебя тут не очень удобно отдаются фильмы из хранилища... отдавай как список а не карту.

2022-09-29 20:14 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +        return commonFriendsId.stream().map(item -> userStorage.getById(item)).collect(Collectors.toList());
перед `return` всегда делаем отступ - пустую строку. Чтобы визуально выделить завершение.

Не нужно делать отступ только если метод сразу начинается с `return`.

Ну и снова прокомментирую. В цепочках, в стримах, важно каждую операцию ставить на новую строку.

```
        return commonFriendsId.stream()
                              .map(item -> userStorage.getById(item))
                              .collect(Collectors.toList());
```

2022-09-29 20:14 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storages/FilmStorage.java
> +    HashMap<Long, Film> getAll();
Вот тут почему не List ?

2022-09-29 20:14 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storages/UserStorage.java
> +public interface UserStorage {
Тебе не кажутся два интерфейса похожими?
Можешь что-то с этим сделать?

2022-09-30 14:57 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +
Fixed

2022-09-30 14:58 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +import org.springframework.web.bind.annotation.DeleteMapping;
Fixed. На самом деле я специально убирал * так как когда-то мне говорили что лучше е убирать)

2022-09-30 14:59 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/IncorrectParameterException.java
> +public class IncorrectParameterException extends RuntimeException {
Fixed

2022-09-30 15:07 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +    @Value("${server.minDate}")
Fixed

2022-09-30 15:27 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +        var sorted = films.stream().sorted((f1, f2) -> f2.getLikeUsers().size() - f1.getLikeUsers().size()).collect(Collectors.toList());
Fixed

2022-09-30 15:28 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +        return commonFriendsId.stream().map(item -> userStorage.getById(item)).collect(Collectors.toList());
fixed

2022-09-30 15:29 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/storages/FilmStorage.java
> +    HashMap<Long, Film> getAll();
Fixed.

2022-09-30 19:18 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +import org.springframework.web.bind.annotation.DeleteMapping;
ну слушай странно я нигде никогда не встречал чтобы с этим так заморачивались...

2022-09-30 22:03 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/storages/UserStorage.java
> +public interface UserStorage {
FIxed. Сделал интерейс дженериковым

2022-10-01 00:17 UTC, FanaticFiz approved these changes

2022-10-01 00:17 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storages/Storage.java
> +    boolean isContainValue(long id);
`isContainValue -> isExist` ?

2022-10-01 00:17 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storages/InMemoryUserStorage.java
> +        if (users.values().stream()
Не заметил в первой итерации...
Не подставляй в условие такую сложную конструкцию. В крайнем случае нужно вынести это в метод, и осмысленно назвать - всё ради того чтобы условие читалось и было коротким.

Ну а вообще, в этом случае, можно просто написать всё в функциональном стиле

```
        users.values().stream()
             .filter(u -> u.getEmail().equals(user.getEmail()))
             .findFirst()
             .ifPresent(user1 -> {
                 throw new AlreadyExistException("User account with email " + user.getEmail() + " is already exist.");
             });
```

2022-10-01 00:17 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storages/InMemoryFilmStorage.java
> +        } else {
Тут тоже возможен рефакторинг.
- else можно просто удалить и избежать лишней вложенности
- затем избавиться от existedFilm - как в предыдущем примере

2022-10-01 06:57 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/storages/Storage.java
> +    boolean isContainValue(long id);
Fixed

2022-10-01 07:00 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/storages/InMemoryUserStorage.java
> +        if (users.values().stream()
Fixed

2022-10-01 07:24 UTC, AlexanderSharygin commented on src/main/java/ru/yandex/practicum/filmorate/storages/InMemoryFilmStorage.java
> +        } else {
Не уверен что тут у меня получится сделать по аналогии с предыдущим примером - мне ведь надо в любом случае найти фильм в хранилище что бы обновить его

2022-10-01 07:26 UTC, merged